setting:
  name: "test_ntu_viral"
  output_root: "./experiments"
  deskew: True
process:
  min_range_m: 3.0
  max_range_m: 80.0
sampler:
  surface_sample_range_m: 0.25
  surface_sample_n: 4
  free_sample_begin_ratio: 0.5
  free_sample_end_dist_m: 1.0
  free_front_sample_n: 2
neuralpoints:
  search_alpha: 0.5
  weighted_first: False
loss:
  loss_weight_on: True
  dist_weight_scale: 0.8
  ekional_loss_on: True
  weight_e: 0.5
continual:
  batch_size_new_sample: 3000
  pool_capacity: 5e6
  pool_filter_freq: 10
tracker:
  iter_n: 100
pgo:
  map_context: True
  pgo_freq_frame: 30
  virtual_side_count: 6
optimizer: # mapper
  iters: 15 # iterations per frame
  batch_size: 8192
eval:
  mesh_freq_frame: 50 # reconstruct the mesh every x frames
  mesh_min_nn: 15
sensor_fusion:
  main_sensor: # from *.txt
    # imu:
    #   topic: /imu/imu
    #   extrinsic_main_main: [1., 0., 0., 0.0,
    #                           0., 1., 0., 0.0,
    #                           0., 0., 1., 0.0]
    lidar:
      topic: /velodyne_points
      extrinsic_main_main: [ 1.0,   0.0,  0.0, -0.050,
                              0.0,  -1.0,  0.0,  0.000,
                              0.0,  0.0,  -1.0,  0.055,
                              0.0,  0.0,  0.0,  1.000 ]
      deskew: true
      preprocess: true
      max_range: 100.0 
      min_range: 5.0
      max_points_per_voxel: 20
      voxel_size: 1
      max_iteration: 1
  sensor_types: 
    imu:
      - topic: /imu/imu
        extrinsic_main_imu: [ 1.0,  0.0,  0.0,  0.0,
                              0.0, -1.0,  0.0,  0.0,
                              0.0,  0.0, -1.0,  0.0,
                              0.0,  0.0,  0.0,  1.0 ]
        # IMU noise parameters
        arw: [ 0.000433, 0.000433, 0.000433 ]          # [deg/sqrt(hr)]
        vrw: [ 2.66e-05, 2.66e-05, 2.66e-05 ]          # [m/s/sqrt(hr)]
        gbstd: [0.0365432018302, 0.0365432018302, 0.0365432018302]        # [deg/hr]
        abstd: [0.00367396706572, 0.00367396706572, 0.00367396706572]     # [mGal]
        corrtime: 1.0                    # [hr]
        init_pos_std: [ 0.01, 0.01, 0.01 ]
        init_vel_std: [ 0.05, 0.05, 0.05 ]
        init_att_std: [ 0.1, 0.1, 0.1 ]
        imu_tran_R: [ [ 1, 0, 0],
                      [ 0, 1, 0],
                      [ 0, 0, 1]]
        hz: 385
      - topic: /os1_cloud_node1/imu
        extrinsic_main_imu: [ 1.0,  0.0,  0.0, -0.050,
                              0.0, -1.0,  0.0,  0.000,
                              0.0,  0.0, -1.0,  0.055,
                              0.0,  0.0,  0.0,  1.000 ]
        # IMU noise parameters
        arw: [2, 2, 2]          # [deg/sqrt(hr)]
        vrw: [40, 40, 40]          # [m/s/sqrt(hr)]
        gbstd: [200.0, 200.0, 200.0]        # [deg/hr]
        abstd: [500.0, 500.0, 500.0]     # [mGal]
        corrtime: 1.0                    # [hr]
        init_pos_std: [ 0.01, 0.01, 0.01 ]
        init_vel_std: [ 0.05, 0.05, 0.05 ]
        init_att_std: [ 0.1, 0.1, 0.1 ]
        imu_tran_R: [ [ 1, 0, 0],
                      [ 0, 1, 0],
                      [ 0, 0, 1]]
        hz: 100
      - topic: /os1_cloud_node2/imu
        extrinsic_main_imu: [  -1,    0,    0, -0.550,
                                0,    0,   -1,  0.030,
                                0,   -1,    0,  0.050,
                              0.0,  0.0,  0.0,  1.000 ]
        # IMU noise parameters
        arw: [2, 2, 2]          # [deg/sqrt(hr)]
        vrw: [40, 40, 40]          # [m/s/sqrt(hr)]
        gbstd: [200.0, 200.0, 200.0]        # [deg/hr]
        abstd: [500.0, 500.0, 500.0]     # [mGal]
        corrtime: 1.0                    # [hr]
        init_pos_std: [ 0.01, 0.01, 0.01 ]
        init_vel_std: [ 0.05, 0.05, 0.05 ]
        init_att_std: [ 0.1, 0.1, 0.1 ]
        imu_tran_R: [ [-1.,  0.,  0.],
                      [ 0.,  0.,  1.],
                      [ 0.,  1.,  0.]]
        hz: 100
    # lidar:
    #   - topic: /os1_cloud_node1/points
    #     extrinsic_main_lidar: [ 1.0,  0.0,  0.0, -0.050,
    #                             0.0,  1.0,  0.0,  0.000,
    #                             0.0,  0.0,  1.0,  0.055,
    #                             0.0,  0.0,  0.0,  1.000 ]
    #   - topic: /os1_cloud_node2/points
    #     extrinsic_main_lidar: [-1.0,  0.0,  0.0, -0.550,
    #                             0.0,  0.0,  1.0,  0.030,
    #                             0.0,  1.0,  0.0,  0.050,
    #                             0.0,  0.0,  0.0,  1.000 ]
                              




                              